options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: maven:3.8.5-jdk-11
    entrypoint: 'mvn'
    args: ['clean','install']
  #  - name: maven:3.8.5-jdk-11
  #    entrypoint: 'mvn'
  #    args: [ 'test' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c','pwd']
    timeout: '1600s'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c','ls' ]
    timeout: '1600s'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && cd /workspace/service1/target/ && gcloud app deploy /workspace/service1-app.yaml' ]
    timeout: '1600s'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && cd /workspace/service2/target/ && gcloud app deploy /workspace/service2-app.yaml' ]
    timeout: '1600s'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && cd /workspace/service3/target/ && gcloud app deploy /workspace/service3-app.yaml' ]
    timeout: '1600s'